export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const CREATE_CATEGORY_RESET = 'CREATE_CATEGORY_RESET';

export const GET_ALL_CATEGORY_REQUEST = 'GET_ALL_CATEGORY_REQUEST';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAIL = 'GET_ALL_CATEGORY_FAIL';
export const GET_ALL_CATEGORY_RESET = 'GET_ALL_CATEGORY_RESET';
