export const CAROUSEL_CREATE_REQUEST = 'CAROUSEL_CREATE_REQUEST';
export const CAROUSEL_CREATE_SUCCESS = 'CAROUSEL_CREATE_SUCCESS';
export const CAROUSEL_CREATE_FAIL = 'CAROUSEL_CREATE_FAIL';
export const CAROUSEL_CREATE_RESET = 'CAROUSEL_CREATE_RESET';

export const CAROUSEL_GET_REQUEST = 'CAROUSEL_GET_REQUEST';
export const CAROUSEL_GET_SUCCESS = 'CAROUSEL_GET_SUCCESS';
export const CAROUSEL_GET_FAIL = 'CAROUSEL_GET_FAIL';
export const CAROUSEL_GET_RESET = 'CAROUSEL_GET_RESET';

export const CAROUSEL_UPDATE_REQUEST = 'CAROUSEL_UPDATE_REQUEST';
export const CAROUSEL_UPDATE_SUCCESS = 'CAROUSEL_UPDATE_SUCCESS';
export const CAROUSEL_UPDATE_FAIL = 'CAROUSEL_UPDATE_FAIL';
export const CAROUSEL_UPDATE_RESET = 'CAROUSEL_UPDATE_RESET';

export const CAROUSEL_DELETE_REQUEST = 'CAROUSEL_DELETE_REQUEST';
export const CAROUSEL_DELETE_SUCCESS = 'CAROUSEL_DELETE_SUCCESS';
export const CAROUSEL_DELETE_FAIL = 'CAROUSEL_DELETE_FAIL';
export const CAROUSEL_DELETE_RESET = 'CAROUSEL_DELETE_RESET';

export const CAROUSEL_BY_ID_REQUEST = 'CAROUSEL_BY_ID_REQUEST';
export const CAROUSEL_BY_ID_SUCCESS = 'CAROUSEL_BY_ID_SUCCESS';
export const CAROUSEL_BY_ID_FAIL = 'CAROUSEL_BY_ID_FAIL';
export const CAROUSEL_BY_ID_RESET = 'CAROUSEL_BY_ID_RESET';
